# Generated by Django 5.2.7 on 2025-11-09 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField()),
                ('reason', models.TextField()),
                ('report_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('ongoing', 'Ongoing')], default='open', max_length=20)),
                ('handled_by', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_made', to=settings.AUTH_USER_MODEL)),
                ('target_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
