# Generated by Django 5.1 on 2026-07-09 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('idea', 'Idea Phase'), ('building', 'Building'), ('launched', 'Launched')], default='idea', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Startup Project',
                'verbose_name_plural': 'Startup Projects',
                'db_table': 'startup_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('is_filled', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='launchpad.startupproject')),
            ],
            options={
                'verbose_name': 'Project Role',
                'verbose_name_plural': 'Project Roles',
                'db_table': 'project_roles',
            },
        ),
    ]
