# Generated by Django 5.0.1 on 2026-01-27 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listings'),
        ),
        migrations.AddField(
            model_name='savedlisting',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='listings.listings'),
        ),
        migrations.AddField(
            model_name='savedlisting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='listings',
            index=models.Index(fields=['status', '-created_at'], name='listings_status_174ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='listings',
            index=models.Index(fields=['category', 'status'], name='listings_categor_7f7673_idx'),
        ),
        migrations.AddIndex(
            model_name='listings',
            index=models.Index(fields=['seller', 'status'], name='listings_seller__9c3ec9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedlisting',
            unique_together={('user', 'listing')},
        ),
    ]
