# Generated by Django 5.2.7 on 2025-11-09 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='status',
            new_name='listing_status',
        ),
        migrations.AlterField(
            model_name='listings',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
