# Generated by Django 5.0.1 on 2026-03-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='backend/media/listing_images/'),
        ),
    ]
