# Generated by Django 5.0.1 on 2026-09-14 21:16

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_category_slug_listings_listing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(storage=backend.storage_backends.MediaStorage(), upload_to='listing_images/'),
        ),
    ]
