# Generated by Django 5.0.1 on 2026-09-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_backfill_listing_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='pricing_unit',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('hourly', 'Per Hour')], default='fixed', max_length=20),
        ),
    ]
