# Generated by Django 5.0.1 on 2026-09-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listings_pricing_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
