# Generated by Django 5.0.1 on 2026-09-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyer_otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_otp_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
