# Generated by Django 5.0.1 on 2026-04-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
