# Generated by Django 5.1 on 2026-07-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_university_is_verified_waitlistentry_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni'), ('organization', 'Organization')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
