# Generated by Django 5.0.1 on 2026-08-26 18:38

import backend.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_role_university_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=backend.storage_backends.AvatarStorage(), upload_to='profile_pictures/'),
        ),
    ]
